server:
  port: 8080
  servlet:
    context-path: /
info:
  app:
    name: '@project.artifactId@'
    description: '@project.description@'
    version: '@project.version@'

spring:
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
      pool-name: ${spring.application.name}-pool
    name: ${spring.application.name}-ds
  application:
    name: '@project.artifactId@'
  profiles:
    default: mysql
  boot:
    admin:
      client:
        enabled: false
  cloud:
    kubernetes:
      enabled: true
  zipkin:
    enabled: false
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        # disabled while hibernate bug is opened: https://hibernate.atlassian.net/browse/HHH-13280
        use_sql_comments: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
        connection:
          provider_disables_autocommit: true
        generate_statistics: true
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
          batch_size: 50
        order_updates: true
        order_inserts: true
      org.hibernate.flushMode: COMMIT
    hibernate:
      connection:
        provider_disables_autocommit: true
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  liquibase:
    contexts: ${spring.profiles.active}
    change-log: 'classpath:/db/changelog/db.master.xml'
logging:
  level:
    root: INFO
    br.com.fiap: INFO