server:
  port: 8080
  servlet:
    context-path: /
info:
  app:
    name: '@project.artifactId@'
    description: '@project.description@'
    version: '@project.version@'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech-challenge-db?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
    username: root
    password: root
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  liquibase:
    contexts: ${spring.profiles.active}
    change-log: 'classpath:/db/changelog/db.master.xml'
logging:
  level:
    root: INFO
    br.com.fiap: INFO